version: "3.9"
services:
  app:
    build:
      context: "."
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
  repro:
    build:
      context: "."
    depends_on:
      - app
      - nginx
    command: ./repro.py
